/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Roshan
 */

import java.util.Date;

public class ATMGUI extends javax.swing.JFrame {

    private boolean numberButtonsEnabled = true;
    private boolean menuButtonsEnabled = false;
    private boolean hideInputNumbers = true;
    String whatisbeingInput = "PIN";
    String inputNumbers = "";
    private boolean withdraw = false;
    
    private int Pin_attempts = 0;
     
  Customer Roshan=new Customer("Roshan", "Arun Kumar","000601345");
  BankAccount account= Roshan.getAccount("0000000001");
        
            
    
   
    /**
     * Creates new form ATMGUI
     */
    public ATMGUI() {
        initComponents();
        Roshan.addAccount(new BankAccount(BankAccount.ACCOUNT_TYPE_CURRENT,"0000000001","000001"));
        numberButtons_mode();
        MessageText.setText("Enter your pin please");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TextLabel = new javax.swing.JLabel();
        MessageText = new javax.swing.JLabel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnStatement = new javax.swing.JButton();
        btnChangePin = new javax.swing.JButton();
        btnLogOff = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        LabelBalance = new javax.swing.JLabel();
        LabelWithdraw = new javax.swing.JLabel();
        LabelDeposit = new javax.swing.JLabel();
        LabelStatement = new javax.swing.JLabel();
        LabelChangePin = new javax.swing.JLabel();
        LabelLogOff = new javax.swing.JLabel();
        Display = new javax.swing.JScrollPane();
        DisplayText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        TextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        TextLabel.setForeground(new java.awt.Color(0, 204, 0));
        TextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(TextLabel, gridBagConstraints);

        MessageText.setForeground(new java.awt.Color(51, 255, 0));
        MessageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(MessageText, gridBagConstraints);

        btnOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy.jpg"))); // NOI18N
        btnOne.setToolTipText("");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnOne, gridBagConstraints);

        btnTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 2.jpg"))); // NOI18N
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnTwo, gridBagConstraints);

        btnThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 3.jpg"))); // NOI18N
        btnThree.setOpaque(true);
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnThree, gridBagConstraints);

        btnFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 4.jpg"))); // NOI18N
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFour, gridBagConstraints);

        btnFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 5.jpg"))); // NOI18N
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFive, gridBagConstraints);

        btnSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 6.jpg"))); // NOI18N
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSix, gridBagConstraints);

        btnSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 7.jpg"))); // NOI18N
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSeven, gridBagConstraints);

        btnEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 8.jpg"))); // NOI18N
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnEight, gridBagConstraints);

        btnNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 9.jpg"))); // NOI18N
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnNine, gridBagConstraints);

        btnZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 10.jpg"))); // NOI18N
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnZero, gridBagConstraints);

        btnBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnBalance, gridBagConstraints);

        btnWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnWithdraw, gridBagConstraints);

        btnDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnDeposit, gridBagConstraints);

        btnStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnStatement, gridBagConstraints);

        btnChangePin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnChangePin, gridBagConstraints);

        btnLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 14.jpg"))); // NOI18N
        btnLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOffActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnLogOff, gridBagConstraints);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 11.jpg"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnCancel, gridBagConstraints);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 12.jpg"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnClear, gridBagConstraints);

        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tlGsL copy 13.jpg"))); // NOI18N
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnEnter, gridBagConstraints);

        LabelBalance.setBackground(new java.awt.Color(51, 255, 51));
        LabelBalance.setText("Balance");
        LabelBalance.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelBalance, gridBagConstraints);

        LabelWithdraw.setBackground(new java.awt.Color(51, 255, 51));
        LabelWithdraw.setText("Withdraw");
        LabelWithdraw.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelWithdraw, gridBagConstraints);

        LabelDeposit.setBackground(new java.awt.Color(51, 255, 51));
        LabelDeposit.setText("Deposit");
        LabelDeposit.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelDeposit, gridBagConstraints);

        LabelStatement.setBackground(new java.awt.Color(51, 255, 51));
        LabelStatement.setText("Statement");
        LabelStatement.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelStatement, gridBagConstraints);

        LabelChangePin.setBackground(new java.awt.Color(51, 255, 51));
        LabelChangePin.setText("Change Pin");
        LabelChangePin.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelChangePin, gridBagConstraints);

        LabelLogOff.setBackground(new java.awt.Color(51, 255, 51));
        LabelLogOff.setText("Log Off");
        LabelLogOff.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(LabelLogOff, gridBagConstraints);

        Display.setForeground(new java.awt.Color(0, 255, 204));

        DisplayText.setBackground(new java.awt.Color(0, 0, 0));
        DisplayText.setColumns(15);
        DisplayText.setRows(5);
        Display.setViewportView(DisplayText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(Display, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void message_mode(){
        MessageText.setText("");
        TextLabel.setText("");
        inputNumbers = "";
        numberButtonsEnabled = false;
        menuButtonsEnabled = false;
        TextLabel.setVisible(true);
       
        
        LabelBalance.setVisible(false);
        LabelDeposit.setVisible(false);
        LabelWithdraw.setVisible(false);
        LabelStatement.setVisible(false);
        LabelChangePin.setVisible(false);
        LabelLogOff.setVisible(false);
        
    }
    
    
    
    
    private void menuButtons_mode(){
        MessageText.setText("");
        TextLabel.setText("");
        inputNumbers = "";
        numberButtonsEnabled = false;
        menuButtonsEnabled = true;
        TextLabel.setVisible(false);
       
        
        LabelBalance.setVisible(true);
        LabelDeposit.setVisible(true);
        LabelWithdraw.setVisible(true);
        LabelStatement.setVisible(true);
        LabelChangePin.setVisible(true);
        LabelLogOff.setVisible(true);
        
    }
    
    
    
    private void numberButtons_mode(){
        MessageText.setText("");
        DisplayText.setText("");
        numberButtonsEnabled = true;
        menuButtonsEnabled = false;
        TextLabel.setText("");
        inputNumbers = "";
        TextLabel.setVisible(true);
        
        
        LabelBalance.setVisible(false);
        LabelDeposit.setVisible(false);
        LabelWithdraw.setVisible(false);
        LabelStatement.setVisible(false);
        LabelChangePin.setVisible(false);
        LabelLogOff.setVisible(false);
        

                
    }
    
     private void addNumber(String num){

        
        if (numberButtonsEnabled){
            inputNumbers=inputNumbers.concat(num);
            if (!hideInputNumbers){
                
               TextLabel.setText(inputNumbers);
            }
            else{
                StringBuffer stars = new StringBuffer(inputNumbers.length());
                for (int i=0;i<inputNumbers.length();i++){
                    stars.append("*");
                }
                TextLabel.setText(stars.toString());
            }
        }
    }
            
            
    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        addNumber("1");
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        addNumber("3");
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
       addNumber("2");
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
       addNumber("4");
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        addNumber("5");
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
addNumber("6");
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
addNumber("7");
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
addNumber("8");
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
addNumber("9");
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
addNumber("0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        menuButtons_mode();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        String DisplayTxt = TextLabel.getText();
        if (DisplayTxt.length() > 0) {
            String afterDelete = DisplayTxt.substring(0,DisplayTxt.length()-1);
            TextLabel.setText(afterDelete);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
      //returns to menu after doing an action// 
        if (whatisbeingInput.equals("return")){
            menuButtons_mode();
        }
        
        
        if (whatisbeingInput.equals("PINCHANGE")){
            if (inputNumbers.length()== 6){
                Roshan.getAccount("0000000001").setPinNumber(inputNumbers);
                 MessageText.setText("Your pin has been changed");
                hideInputNumbers = false;
                whatisbeingInput = "return";
            }
            else {
                MessageText.setText("Pin is too short or too long please try again ");
                whatisbeingInput = "return";
            }
           
        }
        
        //Checks the pin//
        if (whatisbeingInput.equals("PIN") || whatisbeingInput.equals("CHANGEPIN")) {
            if (Roshan.getAccount("0000000001").checkPin(inputNumbers)){
                Pin_attempts = 0;
                if (whatisbeingInput.equals("CHANGEPIN")){
                    TextLabel.setText("");
                    inputNumbers = "";
                    MessageText.setText("Please enter your new pin");
                    whatisbeingInput = "PINCHANGE";
                }
                else{
                    hideInputNumbers = false;
                    menuButtons_mode();
                }
                
                
            }
            else {
                Pin_attempts += 1;
                TextLabel.setText("");
                inputNumbers = "";
                MessageText.setText("Wrong pin please try again");
                if (Pin_attempts >= 3){
                    setVisible(false);
                    dispose();
                }
            }
        }
        //withdraw money//
        if (whatisbeingInput.equals("withdraw")){
            Double x = Double.parseDouble(inputNumbers);
           if (Roshan.getAccount("0000000001").getBalance()>= x) {
            Roshan.getAccount("0000000001").addTransaction(new Transactions(new Date(),Transactions.TRANS_TYPE_WITHDRAWAL,x));
            MessageText.setText("New Balance is");
            inputNumbers = Double.toString(Roshan.getAccount("0000000001").getBalance());
            TextLabel.setText(inputNumbers);
            whatisbeingInput = "return";
           }
           else {
                numberButtons_mode();
                MessageText.setText("Insufficient Funds");
                whatisbeingInput="return";
            }
           
        }
        
        if (whatisbeingInput.equals("deposit")) {
            Double y =Double.parseDouble(inputNumbers);
            Roshan.getAccount("0000000001").addTransaction(new Transactions(new Date(),Transactions.TRANS_TYPE_DEPOSIT,y));
            MessageText.setText("New Balance is");
            inputNumbers = Double.toString(Roshan.getAccount("0000000001").getBalance());
            TextLabel.setText(inputNumbers);
            whatisbeingInput = "return";   
            
          
            
           
        }
            
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        message_mode();
        whatisbeingInput= "return";
        inputNumbers = Double.toString(Roshan.getAccount("0000000001").getBalance());
        TextLabel.setText(inputNumbers);
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        numberButtons_mode();
        MessageText.setText("How much would you like to withdraw");
        whatisbeingInput="withdraw";
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
    numberButtons_mode();
    MessageText.setText("How much would you like to deposit");
    whatisbeingInput="deposit";
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatementActionPerformed
       numberButtons_mode();
       String statement = Roshan.getAccount("0000000001").printStatement();
       TextLabel.setText(statement);
       whatisbeingInput = "return";

    }//GEN-LAST:event_btnStatementActionPerformed

    private void btnChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePinActionPerformed
           numberButtons_mode();
           hideInputNumbers = true;
           MessageText.setText("Please enter your current pin");
           whatisbeingInput="CHANGEPIN";
           
          
           
    }//GEN-LAST:event_btnChangePinActionPerformed

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
    hideInputNumbers = true;
    whatisbeingInput = "PIN";
    numberButtons_mode();
    }//GEN-LAST:event_btnLogOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Display;
    private javax.swing.JTextArea DisplayText;
    private javax.swing.JLabel LabelBalance;
    private javax.swing.JLabel LabelChangePin;
    private javax.swing.JLabel LabelDeposit;
    private javax.swing.JLabel LabelLogOff;
    private javax.swing.JLabel LabelStatement;
    private javax.swing.JLabel LabelWithdraw;
    private javax.swing.JLabel MessageText;
    private javax.swing.JLabel TextLabel;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnStatement;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnZero;
    // End of variables declaration//GEN-END:variables
}
